variant = "loose"

[[issues]]
file = "src/StreamLogger.php"
code = "mixed-assignment"
message = "Assigning `mixed` type to a variable may lead to unexpected behavior."
count = 1

[[issues]]
file = "src/StreamLogger.php"
code = "undefined-string-array-index"
message = "Undefined array key 'timestamp' accessed on `array{'channel': string, 'context': array<array-key, mixed>, 'datetime': string, 'extra': array{}, 'level': nonnull, 'level_name': string, 'message': string}`."
count = 1

[[issues]]
file = "tests/src/StreamLoggerTest.php"
code = "mixed-argument"
message = 'Invalid argument type for argument #2 of `phpunit\framework\assert::assertstringcontainsstring`: expected `string`, but found `mixed`.'
count = 1

[[issues]]
file = "tests/src/StreamLoggerTest.php"
code = "mixed-array-access"
message = "Unsafe array access on type `mixed`."
count = 5

[[issues]]
file = "tests/src/StreamLoggerTest.php"
code = "mixed-assignment"
message = "Assigning `mixed` type to a variable may lead to unexpected behavior."
count = 3

[[issues]]
file = "tests/src/StreamLoggerTest.php"
code = "possibly-false-argument"
message = "Argument #1 of function `file_exists` is possibly `false`, but parameter type `string` does not accept it."
count = 1

[[issues]]
file = "tests/src/StreamLoggerTest.php"
code = "possibly-false-argument"
message = "Argument #1 of function `file_get_contents` is possibly `false`, but parameter type `string` does not accept it."
count = 3

[[issues]]
file = "tests/src/StreamLoggerTest.php"
code = "possibly-false-argument"
message = "Argument #1 of function `json_decode` is possibly `false`, but parameter type `string` does not accept it."
count = 3

[[issues]]
file = "tests/src/StreamLoggerTest.php"
code = "possibly-false-argument"
message = "Argument #1 of function `unlink` is possibly `false`, but parameter type `string` does not accept it."
count = 3

[[issues]]
file = "tests/src/StreamLoggerTest.php"
code = "possibly-false-argument"
message = 'Argument #1 of method `waffle\commons\log\streamlogger::__construct` is possibly `false`, but parameter type `string` does not accept it.'
count = 3

[[issues]]
file = "tests/src/StreamLoggerTest.php"
code = "possibly-undefined-array-index"
message = "Possibly undefined array key `string('context')` accessed on `array<array-key, mixed>`."
count = 2

[[issues]]
file = "tests/src/StreamLoggerTest.php"
code = "possibly-undefined-array-index"
message = "Possibly undefined array key `string('level')` accessed on `array<array-key, mixed>`."
count = 1

[[issues]]
file = "tests/src/StreamLoggerTest.php"
code = "possibly-undefined-array-index"
message = "Possibly undefined array key `string('message')` accessed on `array<array-key, mixed>`."
count = 1

[[issues]]
file = "tests/src/StreamLoggerTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\Exception` in `WaffleTests\Commons\Log\StreamLoggerTest::testItWritesJsonLogToStream`.'
count = 1

[[issues]]
file = "tests/src/StreamLoggerTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\ExpectationFailedException` in `WaffleTests\Commons\Log\StreamLoggerTest::testContextInterpolationComplex`.'
count = 1

[[issues]]
file = "tests/src/StreamLoggerTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\ExpectationFailedException` in `WaffleTests\Commons\Log\StreamLoggerTest::testItWritesJsonLogToStream`.'
count = 1

[[issues]]
file = "tests/src/StreamLoggerTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\ExpectationFailedException` in `WaffleTests\Commons\Log\StreamLoggerTest::testSerializationFailureFallback`.'
count = 1

[[issues]]
file = "tests/src/StreamLoggerTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\GeneratorNotSupportedException` in `WaffleTests\Commons\Log\StreamLoggerTest::testItWritesJsonLogToStream`.'
count = 1

[[issues]]
file = "tests/src/StreamLoggerTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `Psr\Log\InvalidArgumentException` in `WaffleTests\Commons\Log\StreamLoggerTest::testContextInterpolationComplex`.'
count = 1

[[issues]]
file = "tests/src/StreamLoggerTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `Psr\Log\InvalidArgumentException` in `WaffleTests\Commons\Log\StreamLoggerTest::testItThrowsExceptionForInvalidStream`.'
count = 1

[[issues]]
file = "tests/src/StreamLoggerTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `Psr\Log\InvalidArgumentException` in `WaffleTests\Commons\Log\StreamLoggerTest::testItWritesJsonLogToStream`.'
count = 1

[[issues]]
file = "tests/src/StreamLoggerTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `Psr\Log\InvalidArgumentException` in `WaffleTests\Commons\Log\StreamLoggerTest::testSerializationFailureFallback`.'
count = 1
