variant = "loose"

[[issues]]
file = "src/StreamLogger.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "src/StreamLogger.php"
code = "explicit-octal"
message = "Use explicit octal numeral notation."
count = 1

[[issues]]
file = "src/StreamLogger.php"
code = "literal-named-argument"
message = "Literal argument `'ab'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "src/StreamLogger.php"
code = "no-error-control-operator"
message = "Unsafe use of error control operator `@`."
count = 2

[[issues]]
file = "src/StreamLogger.php"
code = "prefer-early-continue"
message = "Consider using early continue pattern to reduce nesting."
count = 1

[[issues]]
file = "tests/src/AbstractTestCase.php"
code = "no-redundant-method-override"
message = "Redundant method override."
count = 2

[[issues]]
file = "tests/src/StreamLoggerTest.php"
code = "assertion-style"
message = "Inconsistent assertions style."
count = 10

[[issues]]
file = "tests/src/StreamLoggerTest.php"
code = "literal-named-argument"
message = "Literal argument `'waffle_log_fail'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "tests/src/StreamLoggerTest.php"
code = "literal-named-argument"
message = "Literal argument `'waffle_log_interpolate'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "tests/src/StreamLoggerTest.php"
code = "literal-named-argument"
message = "Literal argument `'waffle_log_test'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "tests/src/StreamLoggerTest.php"
code = "literal-named-argument"
message = "Literal argument `true` should be passed as a named argument for clarity."
count = 3
